version: '3'

services:
  db:
    image: postgres:13.6-alpine3.15
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./storage/docker/_db:/var/lib/postgresql/data
